cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<uuid:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<uuid:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<uuid:product_id>', views.full_remove, name='full_remove'),
    path('new_order/', views.create_order, name='new_order'),
]

online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')), 
    path('accounts/', include('accounts.urls')), 
    path('',include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('vouchers/', include('vouchers.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.prod_list, name = 'all_products'),
    path('<uuid:category_id>/', views.prod_list, name = 'products_by_category'),
    path('<uuid:category_id>/<uuid:product_id>/', views.product_detail, name = 'product_detail'),
]

vouchers/urls.py
from django.urls import path
from . import views

app_name = 'vouchers'

urlpatterns = [
    path('apply/', views.voucher_apply, name='apply'),
]

cart/models.py
from django.db import models
from shop.models import Product

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    active = models.BooleanField(default=True)
    
    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        if self.product.is_sale:
            return self.product.sale_price * self.quantity
        else:
            return self.product.price * self.quantity

    def __str__(self):
        return self.product

cart/views.py
import stripe
from django.conf import settings
from django.urls import reverse
from django.shortcuts import redirect, render, get_object_or_404
from shop.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from order.models import Order, OrderItem
from stripe import StripeError
from vouchers.models import Voucher
from vouchers.forms import VoucherApplyForm
from decimal import Decimal


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist: 
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if (cart_item.quantity < cart_item.product.stock):
            cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, quantity=1,cart=cart)
    return redirect('cart:cart_detail') 


def cart_detail(request, total=0, counter=0, cart_items = None):
    discount = 0
    voucher_id = 0
    new_total = 0
    voucher = None
    
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass

    stripe.api_key = settings.STRIPE_SECRET_KEY
    stripe_total = int(total * 100)  # Convert total to cents
    description = 'Online Shop - New Order'
    voucher_apply_form = VoucherApplyForm()

    try:
        voucher_id = request.session.get('voucher_id')
        voucher = Voucher.objects.get(id=voucher_id)
        if voucher != None:
            discount = (total*(voucher.discount/Decimal('100')))
            new_total = (total - discount)
            stripe_total = int(new_total * 100)
    except:
        ObjectDoesNotExist
        pass


    if request.method == 'POST':
        try:
            # Create a new Stripe Checkout session
            checkout_session = stripe.checkout.Session.create(
                payment_method_types=['card'],
                line_items=[{
                    'price_data': {
                        'currency': 'eur',
                        'product_data': {
                            'name': 'Order from Connect Zero',
                        },
                        'unit_amount': stripe_total,
                    },
                    'quantity': 1,
                }],
                mode='payment',
 		   billing_address_collection='required', 
                shipping_address_collection={},
                payment_intent_data={'description': description},
                success_url=request.build_absolute_uri(reverse('cart:new_order'))+ f"?session_id={{CHECKOUT_SESSION_ID}}&voucher_id={voucher_id}&cart_total={total}",
                cancel_url=request.build_absolute_uri(reverse('cart:cart_detail')),    
            )
            # Redirect to Stripe Checkout
            return redirect(checkout_session.url, code=303)
        except Exception as e:
            # Render the template with an error message
            return render(request, 'cart.html', {
                'cart_items': cart_items,
                'total': total,
                'counter': counter,
                'error': str(e),  # Display error if there's an issue with Stripe
            })

    return render(request, 'cart.html', {
        'cart_items': cart_items,
        'total': total,
        'counter': counter,
        'voucher_apply_form': voucher_apply_form,
        'new_total': new_total,
        'voucher': voucher,
        'discount': discount
    })

def cart_remove(request, product_id):
    cart= Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

def empty_cart(request):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        cart_items.delete()  
        cart.delete()
        return redirect('shop:all_products')
    except Cart.DoesNotExist:
        pass
    return redirect('cart:cart_detail')

def create_order(request):
    try:
        session_id = request.GET.get('session_id')
        cart_total = request.GET.get('cart_total')
        voucher_id = request.GET.get('voucher_id')
        if not session_id:
            raise ValueError("Session ID not found.")

        try:
            session = stripe.checkout.Session.retrieve(session_id)
        except StripeError as e:
            return redirect("shop:all_products") 

        customer_details = session.customer_details
        if not customer_details or not customer_details.address:
            raise ValueError("Missing information in the Stripe session.")

        billing_address = customer_details.address
        billing_name = customer_details.name
        shipping_address = customer_details.address
        shipping_name = customer_details.name

        try:
            order_details = Order.objects.create(
                token=session.id,
                total=session.amount_total / 100,  # Convert cents to currency units
                emailAddress=customer_details.email,
                billingName=billing_name,
                billingAddress1=billing_address.line1,
                billingCity=billing_address.city,
                billingPostcode=billing_address.postal_code,
                billingCountry=billing_address.country,
                shippingName=shipping_name,
                shippingAddress1=shipping_address.line1, 
                shippingCity=shipping_address.city, 
                shippingPostcode=shipping_address.postal_code,
                shippingCountry=shipping_address.country,
            )
            order_details.save()
        except Exception as e: 
            print(f"Error: {e}")
            return redirect("shop:all_products") 

        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, active=True)
        except ObjectDoesNotExist:
            return redirect("shop:all_products")  
        except Exception as e:
            print(f"Error: {e}")
            return redirect("shop:all_products")  
        
        voucher = get_object_or_404(Voucher, id=voucher_id)
        if voucher != None:
            order_details.voucher = voucher
            cart_total = Decimal(cart_total)
            order_details.discount = cart_total*(voucher.discount/Decimal('100'))
            order_details.total = (cart_total-order_details.discount)
            order_details.save()
        
        for item in cart_items:
            try:
                oi = OrderItem.objects.create(
                    product=item.product.name,
                    quantity=item.quantity,
                    price=item.product.price,
                    order=order_details
                )
                oi.save()
                '''Reduce stock when order is placed or saved'''
                product = Product.objects.get(id=item.product.id)
                product.stock = int(item.product.stock - item.quantity)
                product.save()
                if voucher != None:
                    discount = (oi.price*(voucher.discount/Decimal('100')))
                    oi.price = (oi.price - discount)
                else:
                    oi.price = oi.price*oi.quantity
                oi.save()
                empty_cart(request)
            except Exception as e:
                return redirect("shop:all_products")  
        return redirect('order:thanks', order_details.id)

    except ValueError as ve:
        print(f"Error: {ve}")
        return redirect("shop:all_products")  

    except StripeError as se:
        print(f"Stripe Error: {se}")
        return redirect("shop:all_products") 

    except Exception as e:
        print(f"Unexpected error: {e}")
        return redirect("shop:all_products") 

cart/templates/cart.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
    This is the shopping cart page. Proceed to review your items and place the order.
{% endblock %}
{% block title %}
    Cart - Connect Zone
{% endblock %}
{% block content %}
    {% if not cart_items %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">
                    Your shopping cart is empty
                </h1>
                <br>
                <p class="text-center">
                    Please click <a href="{% url 'shop:all_products' %}">here</a> to continue shopping.
                </p>
            </div>
        </div>
    {% else %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">
                    Your shopping cart
                </h1>
                <br>
            </div>
        </div>
        <div class="row mx-auto">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class="table my_custom_table">
                    <thead class="my_custom_thead">
                        <tr>
                            <th colspan="5">
                                Your items
                            </th>
                        </tr>
                        
                    </thead>
                    <tbody>
                        {% for cart_item in cart_items %}
                            <tr>
                                <td>
                                    <a href="{{cart_item.product.get_absolute_url}}"><img src="{{cart_item.product.image.url}}" 
                                     alt="" class="float-left rounded custom_image"></a>
                                </td>
                                <td class="text-left">
                                    {{cart_item.product.name}}
                                    <br>
                                    {% if cart_item.product.is_sale %}
                                    Unit Price: €{{cart_item.product.sale_price}}
                                    {% else %}
                                    Unit Price: €{{cart_item.product.price}}
                                    {% endif %}
                                    <br>
                                    {% if cart_item.product.is_sale %}
                                    Qty: {{cart_item.quantity}} x €{{cart_item.product.sale_price}}
                                    {% else %}
                                    Qty: {{cart_item.quantity}} x €{{cart_item.product.price}}
                                    {% endif %}
                                </td>
                                <td>
                                    €{{cart_item.sub_total}}
                                </td>
                                {% if cart_item.quantity < cart_item.product.stock %}
                                    <td>
                                        <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fas fa-plus-circle  
                                           custom_icon"></i></a>&nbsp;
                                        <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus-circle 
                                           custom_icon"></i></a>&nbsp;
                                        <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>
                                    </td>
                                {% else %}
                                    <td>
                                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus-circle 
                                        custom_icon"></i></a>&nbsp;
                                        <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>
                                    </td>
                                    <td></td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class="table my_custom_table">
                    <thead class="my_custom_thead">
                        <tr>
                            <th>
                                Checkout
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                Please review your shopping cart items before proceeding with the order payment.
                            </td>
                        </tr>
                        {% if voucher %}
                        <tr class="subtotal">
                        <td>Total</td>
                        <td colspan="4"></td>
                        <td class="num">€{{ total|floatformat:"2" }}</td>
                        </tr>
                        <tr>
                            <td>
                            "{{ voucher.code }}" voucher
                            ({{ voucher.discount }}% off)
                            </td>
                            <td colspan="4"></td>
                            <td class="num neg">
                            - €{{ discount|floatformat:"2" }}
                            </td>
                        </tr>
                        <tr class="total">
                            <td>Total</td>
                            <td colspan="4"></td>
                            <td class="num">
                                    €{{ new_total|floatformat:"2" }}
                            </td>
                        </tr>
                        {% else %}
                                <tr class="total">
                                    <td>Total</td>
                                    <td colspan="4"></td>
                                    <td class="num">
                                        €{{ total|floatformat:"2" }}
                                    </td>
                                </tr>
                            {% endif %}
                        </tbody>
                    </table>
                    <p>Apply a voucher:</p>
                    <form action="{% url 'vouchers:apply' %}" method="post">
                        {{ voucher_apply_form }}
                        <br>
                        <input type="submit" value="Apply">
                        {% csrf_token %}
                    </form>
                    </tbody>
                </table>
                <!-- Payment Form -->
                 <br>
                <form action="{% url 'cart:cart_detail' %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-secondary btn-block my_custom_button" type="submit">Pay with card</button>
                </form>
                {% if error %}
                  <p style="color: red;">Error: {{ error }}</p>
                {% endif %}
                <div class="mx-auto">
                    <a href="{% url 'shop:all_products' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
                </div>
            </div>
        </div>
        <br>
    {% endif %}
{% endblock %}